POST  http://localhost:3001/api/blogs  HTTP/1.1
content-type: application/json

{
    "author" : "Jari Erävuo",
    "likes" : 2,
    "url": "http://jarinmietteita.fi",
    "title": "Rekrytoinnin haasteita"
}